grid_sizes: [120000, 12000, 6000, 1200, 600, 300]
resolutions: [10]

zones: []  # or leave empty for all
excluded_zones: ["1N", "1S", "60N", "60S"]  # or leave empty for none
default_levels: [300, 600, 1200, 6000, 12000, 120000]


n_workers: 6
memory_limit: 8  # in GB
process_mosaic: false
final_proportions: true
large_factor: 4  # For large grids, increase the factor to avoid memory issues

# Paths
raster_dir: "D:/henarcmeo_hf/datasets_AUX/Landcover/ESA_WorldCover/ESA_LC_tifs"
raster_outline_path: "D:/henarcmeo_hf/datasets_AUX/Landcover/ESA_WorldCover/ESA_LC_tifs/esa_lc_raster_outlines.shp"
grids_dir: "D:/henarcmeo_hf/grids"
output_dir: "D:/henarcmeo_hf/datasets_AUX/Landcover/ESA_WorldCover/ESA_LC_proportions"
