# Grid generation configuration for HenarcmeoGrid

# Define all resolution levels in meters
levels: [2400]
default_levels: [300, 600, 1200, 2400, 12000, 120000]

# Leave utm_zones undefined to process ALL zones (1N–60N, 1S–60S)
# utm_zones: [f"{i}{d}" for i in range(1, 61) for d in ["N", "S"]]

# Output settings
output_format: "PARQUET"                    # Format: PARQUET or SHP
main_path: "D:/henarcmeo_hf/"   # Just the main folder where it is located

# output_dir: "D:/henarcmeo_hf/grids"  # Where to write output

# Optional enhancements
save_geohash: true                          # Save GeoHash column
include_polar: true                        # If True, generates polar grids
skip_existing: true                         # Skip grid generation if output already exists
save_wgs_files: false                        # Export WGS84 versions alongside UTM
save_single_file: false                      # Save full grid as one .parquet per level
generate: false                              # Flag to trigger actual generation (safe for dry-run toggle)

# Optional advanced
# chunked_levels: [300]                       # For large levels, save in multiple chunks
# ref_level: 12000                          # Reference level for spatial alignment
# ref_dir: "D:/henarcmeo_hf/metadata_current/grids_geo/grid_12000m"
