structure:
  datasets_AUX:
    AgriFields: {}
    Buildings:
      Microsoft_Building_Footprints: {}
    DEM:
      GLO30: {}
      SRTM:
        CopDEM30_template.parquet:
          file_type: parquet
          size: 0
        SRTM_template.parquet:
          file_type: parquet
          size: 0
    GHSL_Layers:
      GHSL: {}
      SMOD: {}
    Landcover:
      ESA_WorldCover:
        ESA_LC_proportions: {}
        ESA_LC_tifs: {}
        ESA_WorldCover_template.parquet:
          file_type: parquet
          size: 0
      ESRI_LC:
        '2024':
          ESRI_LULC_template.parquet:
            file_type: parquet
            size: 0
    OSM: {}
  datasets_EO:
    GE_Base: {}
    Landsat: {}
    Maxar: {}
    MODIS: {}
    Neon: {}
    S1RTC: {}
    S2L2A: {}
    S3: {}
    S5-P: {}
    Satellogic: {}
    Umbra: {}
    Wvyne: {}
  embeddings:
    SAM:
      GE_Base_05: {}
      S2RGB: {}
    SAM2: {}
    SigLip: {}
    SSL4EO: {}
  grids:
    grid_120000m: {}
    grid_12000m: {}
    grid_6000m: {}
    Grids Labels and Levels.txt:
      file_type: txt
      size: 0
    merged_grids: {}
  index_structure: {}
  metadata_current:
    data_metadata:
      data_index.parquet:
        file_type: parquet
        size: 0
    integrity:
      diversity_thresholds.parquet:
        file_type: parquet
        size: 0
    licenses_and_access: {}
    scene_parameters:
      landsat_scene_params.parquet:
        file_type: parquet
        size: 0
      s1rtc_scenes_params.parquet:
        file_type: parquet
        size: 0
      s2l2a_scene_params.parquet:
        file_type: parquet
        size: 0
    sources:
      licenses_and_access.parquet:
        file_type: parquet
        size: 0
      source_catalog.parquet:
        file_type: parquet
        size: 0
    thematic_metadata:
      metadata_climate.parquet:
        file_type: parquet
        size: 0
      metadata_ghsl.parquet:
        file_type: parquet
        size: 0
      metadata_ipcc_forest.parquet:
        file_type: parquet
        size: 0
      metadata_lc.parquet:
        file_type: parquet
        size: 0
      metadata_regions.parquet:
        file_type: parquet
        size: 0
  metadata_previous:
    aux_metadata:
      metadata_climate.parquet:
        file_type: parquet
        size: 0
      metadata_ghsl.parquet:
        file_type: parquet
        size: 0
      metadata_ipcc_forest.parquet:
        file_type: parquet
        size: 0
      metadata_lc.parquet:
        file_type: parquet
        size: 0
      metadata_regions.parquet:
        file_type: parquet
        size: 0
    data_metadata:
      data_index.parquet:
        file_type: parquet
        size: 0
    grids_geo:
      grid_100m.parquet:
        file_type: parquet
        size: 0
      grid_12000.parquet:
        file_type: parquet
        size: 0
      grid_120000.parquet:
        file_type: parquet
        size: 0
      grid_1200m.parquet:
        file_type: parquet
        size: 0
      grid_300m.parquet:
        file_type: parquet
        size: 0
      grid_6000.parquet:
        file_type: parquet
        size: 0
      grid_600m.parquet:
        file_type: parquet
        size: 0
      Grids Labels and Levels.txt:
        file_type: txt
        size: 0
    licenses_and_access: {}
    scene_parameters:
      landsat_scene_params.parquet:
        file_type: parquet
        size: 0
      s1rtc_scenes_params.parquet:
        file_type: parquet
        size: 0
      s2l2a_scene_params.parquet:
        file_type: parquet
        size: 0
    sources:
      eo_aux_sources.parquet:
        file_type: parquet
        size: 0
      licenses_and_access.parquet:
        file_type: parquet
        size: 0
  query_examples: {}
  versions:
    v0_info.txt:
      file_type: txt
      size: 0
